### ISSUE TITLE
Leaving your trail!

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/CubeSurfer#1]
# First Issue Details  

## **Description**:  
This issue is **open to all** contributors as an easy way to get started with Unity and CubeSurfer. Your task is to create a simple prefab in the project.  

## **Tasks**:  
1. Create a Unity prefab that includes a **text object** displaying your name.  
2. Rename the prefab file to your **GitHub username**.  
3. Ensure the prefab is clean, functional, and follows the project's folder structure.

## **Requirements**:  
- The prefab must display your name clearly.  
- Save the prefab in the `Assets/Prefabs` folder (Create if not there).  

## **Submission Guidelines**:  
1. Make sure to pull all the changes before pushing the repo.
2. Submit a pull request (PR) following the [PR template](https://github.com/opencodeiiita/CubeSurfer/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
3. Include a screenshot of your prefab in the Unity editor in the PR description.  

## **Resources**:  
- [Unity Prefabs Documentation](https://docs.unity3d.com/Manual/Prefabs.html)
- [Creating and Using Text in Unity](https://learn.unity.com/tutorial/creating-and-using-text-in-unity)

Feel free to reach out on Discord if you have any questions. This is a great chance to learn and get familiar with the project setup. Happy contributing! 🎮  

Let me know if you'd like any further additions or changes!

**Comment by Gamin8ing** [comment]
Some resources I have linked in the Cubesurfer resource channel of discord server; please do visit that and ask some questions if you have any doubt!

**Comment by TheDivineAurora** [comment]
!claim
