### ISSUE TITLE
Surf's Up! The Cube Awaits Your Command

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/CubeSurfer#13]
# Gameplay mechanics of the game 

This is a **massive first-come, first-serve issue** worth **50 points**. Your task is to set up the basic gameplay mechanics for **CubeSurfer**, which will serve as the foundation for the entire game.  

---

## **Tasks**:  

1. **Camera Setup**:  
   - Position the camera to follow the cube dynamically.  
   - Optionally, you can use **Cinemachine** to enhance the camera's functionality.  

2. **Cube Movement**:  
   - Make the cube move **forward by default**.  
   - Add controls to allow the cube to move **sideways (left and right)** using input keys.  

   > **Note:** there should not be any discripancy regarding the forward axis, that is if `y-axis` is considered as forward it should be followed everywhere.

3. **Collision Handling**:  
   - Check for collisions between the cube and other game objects.  
   - If the cube collides with **anything other than the ground**, stop its forward motion.  
   - Display a `Debug.Log("Game Over")` message in the console.  

4. **Project Structure**:  
   - Follow the existing directory structure.  
   - Avoid adding unnecessary or unrelated components/files.  

> [!CAUTION]
> New input system package should be used, `legacy input manager` should not used!

---

#### **Guidelines**:  
- Ensure your code is clean and modular, with comments explaining key functionalities.  
- Save the scene as `First Level` in the `Assets/Scenes` folder.  
- Name objects and components clearly (e.g., `PlayerCube`, `GameCamera`).  

---

#### **Submission**:  
0. **Most important step!** Always `Sync changes` and `git pull` before creating any PR, as this will avoid heavy merge conflicts to occur.
1. Create a new branch named `add-gameplay-basics-<your-github-username>`.  
2. Submit a pull request (PR) with your implementation.  
3. Attach a short video or GIF showing the cube movement, collision handling, and camera behavior in the PR description.  
4. **Make sure to follow the [PR_template](https://github.com/opencodeiiita/CubeSurfer/blob/main/.github/PULL_REQUEST_TEMPLATE.md) while raising a PR!**

---

#### **Resources**:  

- [Brackeys' Tutorial on gamedev in Unity](https://www.youtube.com/playlist?list=PLPV2KyIb3jR53Jce9hP7G5xC4O9AgnOuL)
- [Unity New Input System](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.11/manual/index.html)
- [Unity Collision Detection](https://docs.unity3d.com/ScriptReference/Collider.OnCollisionEnter.html)
- [Unity Tutorial: Moving Objects with Script](https://learn.unity.com/tutorial/moving-the-player-with-script)

> [!TIP]
> Have any doubt? join the discord server and find the `CubeSurfer` channels category and ask them right away in the `discussion` channel!

Let’s bring CubeSurfer to life with this critical step! 🚀

**Comment by kanav67** [comment]
claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by Gamin8ing** [comment]
Congrats @HGRgamer this issue is assigned to you!

**Comment by Gamin8ing** [comment]
nice work @HGRgamer
