### ISSUE TITLE
Game Over? Level Cleared? Build the UI to Say It All!

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/CubeSurfer#18]
### **Issue Title**: Create UI for CubeSurfer: Score Counter, Game Over, and Level Cleared Screens  

**Points:** `30`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** issue to add essential UI elements to **CubeSurfer**. Your task is to design and implement:  
1. **Score Counter**: A UI element to display the player's score dynamically during gameplay.  
2. **Game Over Screen**: A screen that appears when the game ends, showing a "Game Over" message and an option to retry.  
3. **Level Cleared Screen**: A screen that appears when the player completes a level, showing a congratulatory message and an option to proceed to the next level.  

---

## **Guidelines**:  
1. **Score Counter**:  
   - Place it at a visible position during gameplay (e.g., top-right corner).  
   - Update dynamically as the game progresses.  

2. **Game Over Screen**:  
   - Display a "Game Over" message in large, clear text.  
   - Include a button to restart the game or go back to the main menu. (No need for it to be functional, for now) 

3. **Level Cleared Screen**:  
   - Show a congratulatory message (e.g., "Level Cleared!") in bold, clear text.  
   - Include a button to proceed to the next level.  (Again not functional)

4. **Styling**:  
   - Use Unity's UI components (`Text`, `Buttons`, etc.) to design the screens.  (You can use TextMeshPro for this task, but create a styled and good UI)
   - Ensure the UI is responsive and doesn’t obstruct gameplay.  (**MUST**)

5. **Naming and Structure**:  
   - Save all UI elements in a **Canvas** GameObject and name them appropriately.  
   - **Create a Prefab of all the UI elements in the `Prefabs/UI` folder.**
   - Save the updated scene in `First Level` only.  
   - Do not modify any other files or assets in the repository.  

---

## **Submission Requirements**:  
1. Create a new branch named `add-ui-<your-github-username>` or you can proceed in your `main` branch only.
2. Submit a pull request (PR) with the changes.  
3. Include screenshots and video gameplay of the:  
   - Score Counter during gameplay.  
   - Game Over Screen.  
   - Level Cleared Screen.  
4. Clearly explain your implementation in the PR description.  

---

## **Resources**:  
- [Unity UI Basics](https://learn.unity.com/tutorial/working-with-ui-elements)
- [Unity: Adding Buttons and Text](https://docs.unity3d.com/Manual/UIButton.html)
- [Unity: Canvas and UI Components](https://docs.unity3d.com/Manual/UICanvas.html)  

---

Let’s give CubeSurfer the polished UI it deserves! 🚀

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Navigam1108** [comment]
Claim

**Comment by Gamin8ing** [comment]
Congrats @PriyamJChakrabarty issue goes to you 🎉

**Comment by kanav67** [comment]
@Gamin8ing Can I claim if it is inactive ? (Its been 2+ days)

**Comment by PriyamJChakrabarty** [comment]
Actually I faced a few problems with my laptop...but have started working on it now :' (

**Comment by Gamin8ing** [comment]
Hello @PriyamJChakrabarty this is unfortunately your last day to work on the PR, or the bot will automatically remove the assigned person

**Comment by PriyamJChakrabarty** [comment]
Ok

**Comment by Gamin8ing** [comment]
@PriyamJChakrabarty updates?

**Comment by PriyamJChakrabarty** [comment]
@Gamin8ing reassign it!

**Comment by kanav67** [comment]
claim

**Comment by Gamin8ing** [comment]
congrats @HGRgamer this issue is assigned to you!
