### ISSUE TITLE
Surf’s Start: Create a Stunning Main Menu

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/CubeSurfer#25]
# Create a Main Menu for CubeSurfer  
**Points:** `30`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** UI challenge to design and implement the **Main Menu** for **CubeSurfer**. The Main Menu will be the first scene to appear when the game starts, and it should be functional, creative, and visually appealing.  

---

### **Your Task**:  
1. **Main Menu Design**:  
   - Create a new scene named `MainMenu.unity`.  
   - Add the following buttons:  
     - **Play**: Starts the game by transitioning to the `FirstLevel.unity` scene.  
     - **Options**: Leave this button functional but blank for now (it will be expanded in future tasks).  
     - **Exit**: Exits the game (use `Application.Quit()` for functionality).  

2. **Enhancements**:  
   - Add animations or effects to make the menu visually engaging:  
     - Example: A spinning cube in the background.  
     - Hover effects or animations on the buttons.  
   - Style the menu to align with the game’s theme.  

3. **UI Design**:  
   - Use Unity’s UI components (`Canvas`, `Buttons`, `Text`, etc.) for creating the menu.  
   - Ensure the menu is centered and scales well on different screen resolutions.  

4. **Navigation and Functionality**:  
   - Implement button functionality:  
     - The **Play** button should load `FirstLevel.unity`.  
     - The **Exit** button should close the application.  

---

### **Guidelines**:  
1. Save the new scene in the `Assets/Scenes` directory.  
2. Organize the project hierarchy and name the GameObjects appropriately (e.g., `MainMenuCanvas`, `PlayButton`).  
3. Use Unity’s animation tools or scripts for effects and transitions.  
4. Ensure no other files or assets in the repository are altered.  

---

### **Submission Requirements**:  
1. Create a new branch named `add-main-menu-<your-github-username>`.  
2. Submit a pull request (PR) with the changes.  
3. Attach a **video** and **screenshots** showcasing the main menu’s design, functionality, and animations in the PR description.  

---

### **Resources**:  
- [Unity: Building a Main Menu](https://learn.unity.com/tutorial/live-session-creating-a-main-menu)  
- [Unity Button Click Events](https://docs.unity3d.com/ScriptReference/UI.Button-onClick.html)  
- [Unity Animation Basics](https://learn.unity.com/tutorial/creating-basic-animations)  
- [Application.Quit() Documentation](https://docs.unity3d.com/ScriptReference/Application.Quit.html)  

---

Let’s create an inviting and functional Main Menu to kickstart CubeSurfer! 🚀

**Comment by official-ashutosh** [comment]
claim

**Comment by kanav67** [comment]
claim

**Comment by Gamin8ing** [comment]
sorry @official-ashutosh you already have 3 issues assigned to you
congrats @HGRgamer this issue goes to you 🎉 have fun

**Comment by PHOX-9** [comment]
Claim
