### ISSUE TITLE
Creating your own character...ahem..cube! 

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/CubeSurfer#6]
# Create the Main Character (Cube) and Environment  

## **Description**:  
This is a **first-come, first-serve** issue to help contributors get started with CubeSurfer. Your task is to create the main character (a cube), a plane for the cube to stand on, and align the camera properly to showcase the setup. This forms the foundation of the game environment.  

Refer this as a final result, this is what you are aiming to do!

![image](https://github.com/user-attachments/assets/d643b296-464d-47e6-ace7-c3bf31f21721)

---

## **Your Task**:  
1. **Create the Cube (Main Character)**:  
   - Add a cube to the scene, which will act as the main character.  
   - Position it at the center of the scene and ensure it is slightly above the plane.  
   - Add a suitable material to, how about `Red`? Create a material named `Player` in `Assets/material`, create if not there.
   - make sure to add `Rigidbody`, that is the cube should fall when playing the game.

2. **Add a Plane (Ground)**:  
   - Create a plane below the cube to serve as the ground.  
   - Position it at `0, 0, 0` and ensure it is large enough to cover the camera's view.  

3. **Align the Camera**:  
   - Position and align the camera to focus on the cube and plane.  
   - Ensure the cube is visible in the center of the frame and adjust the camera’s rotation and distance as needed.  

4. **Organize the Scene**:  
   - Name the GameObjects properly (e.g., `MainCube`, `GroundPlane`, `MainCamera`).  
   - Maintain a clean hierarchy for better readability.  
   - **BONUS:** try changing the sybox to a clean colour! (refer to the resources for any additonal help)

5. **Setup the Project for programming!**
   - If you are programming in Visual Studio, or visual studio code, add its associated files accordingly in the `.gitignore` file.
   - also change the `Project Settings` in Unity.

> [!NOTE]
> All the spice will be happening in the `First Level` scene!

> [!TIP]
> You can play with the physics system, try adding rigidbody to various objects and go crazy. But make sure this craziness should not be reflected in the PR lol.
---

## **Guidelines**:  
- Follow Unity's standard practices for naming and organizing assets.  
- Test the scene to ensure the cube, plane, and camera are aligned perfectly.  
- Save the scene.
- Do not break the project flow and add unnecessary files in the PR.

---

## **Submission**:  
1. Create a new branch named `add-main-character-<your-github-username>`.  
2. Submit a pull request (PR) with your changes.  
3. Include a screenshot or short video of your scene in action in the PR description.  

---

## **Resources**:  
- [Unity: Adding Objects to Your Scene](https://learn.unity.com/tutorial/creating-and-manipulating-game-objects)
- [Unity: Understanding the Camera](https://docs.unity3d.com/Manual/class-Camera.html)
- [YouTube Tutorial: Unity Beginner Essentials](https://www.youtube.com/watch?v=IlKaB1etrik&list=PLPV2KyIb3jR53Jce9hP7G5xC4O9AgnOuL&index=2)

Let’s get the basics right and kickstart CubeSurfer together! 🚀

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by kanav67** [comment]
claim

**Comment by kalim-Asim** [comment]
Claim

**Comment by Navigam1108** [comment]
Claim

**Comment by official-ashutosh** [comment]
claim

**Comment by Gamin8ing** [comment]
This issue goes to @HGRgamer 🎉
@PriyamJChakrabarty you already have `3` issues assigned.

**Comment by dev-kanishk293** [comment]
claim

**Comment by Gamin8ing** [comment]
nice work @HGRgamer closed!
